theme: jekyll-theme-cayman
title: Interdisciplinary Approaches to A-Life and the Digital Arts
description: A workshop organized by Xmodal for the 2020 ALife conference \n July 17th 2020 - 5:30pm-8:30pm (Eastern Time)
